name: Deploy docker image

inputs:
  image_tag:
    description: Tag of the docker image to be deployed
    required: true
  github_token:
    required: true
  environment:
    type: choice
    options:
      - testnet
      - mainnet
    required: true
  kustomize_version:
    required: false
    default: "5.1.1"

runs:
  using: composite
  steps:
    - name: GIT | Checkout aleph-apps repo
      uses: actions/checkout@v3
      with:
        repository: Cardinal-Cryptography/aleph-apps
        token: ${{ inputs.github_token }}
        path: "aleph-apps"
        ref: ${{ inputs.environment }}

    - name: KUSTOMIZE | Init kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: ${{ inputs.kustomize_version }}

    - name: KUSTOMIZE | Update docker image tag
      shell: bash
      env:
        DEPLOY_IMAGE: public.ecr.aws/p6e8q1z1/aleph-zero-dashboard:${{ inputs.image_tag }}-${{ inputs.environment }}
      run: |
        cd aleph-apps/aleph-zero-dashboard/overlays/${{ inputs.environment }}/eu-central-1
        kustomize edit set image "aleph-zero-dashboard-image-placeholder=${{ env.DEPLOY_IMAGE }}"
    
    - name: GIT | Commit changes to aleph-apps repository
      uses: EndBug/add-and-commit@v5.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        author_name: AlephZero Automation
        author_email: alephzero@10clouds.com
        message: 'Updating aleph-zero-dashboard ${{ inputs.environment }} docker image tag: ${{ inputs.image_tag }}'
        add: '*.yaml'
        cwd: 'aleph-apps'
        branch: ${{ inputs.environment }}
