name: Build, push and deploy staking dashboard to testnet

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
      - A0-1615-build-pipeline

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: DOCKER | Build and push testnet image
        uses: ./.github/actions/build-and-push
        id: build_testnet
        with:
          environment: testnet
          build_envs: "REACT_APP_DISABLE_MAINNET=1 REACT_APP_DISABLE_FIAT=1"
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
    outputs:
      image_tag: ${{ steps.build_testnet.outputs.image_tag }}
