name: Build, push and deploy Aleph Zero Dashboard to devnet

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-20.04
    environment:
      name: devnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v4

      - name: Build and push devnet image
        uses: ./.github/actions/build-and-push
        id: build-devnet
        with:
          environment: devnet
          build_envs: 'VITE_DISABLE_FIAT=1'
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
    outputs:
      image_tag: ${{ steps.build-devnet.outputs.image_tag }}

  deploy-to-devnet:
    name: Deploy to devnet
    runs-on: ubuntu-20.04
    needs: [build-and-push]
    environment:
      name: devnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v4

      - name: Deploy Aleph Zero Dashboard to Devnet
        uses: ./.github/actions/deploy
        id: deploy-devnet
        with:
          environment: devnet
          kustomize_version: ${{ vars.KUSTOMIZE_VERSION }}
          autocommit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          autocommit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          autocommit-gpg-key-b64: ${{ secrets.AUTOCOMMIT_GPG_KEY_B64 }}
          autocommit-gpg-key-fingerprint: ${{ secrets.AUTOCOMMIT_GPG_KEY_FINGERPRINT }}
          image_tag: ${{ needs.build-and-push.outputs.image_tag }}
          github_token: ${{ secrets.CI_GH_TOKEN }}

  slack-notification:
    name: Slack notification
    runs-on: ubuntu-20.04
    needs: [deploy-to-devnet]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Slack message
        uses: Cardinal-Cryptography/github-actions/slack-notification@v6
        with:
          notify-on: "failure"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_DEV_ONDUTY }}
